const productos = [
    {
        id:1,
        productName:"Banana",
        price:480,
        quantly:1,
        img:"/client/media/banana.png"
    },
    {
        id:2,
        productName:"Leche",
        price:950,
        quantly:1,
        img:"/client/media/leche.png"
    },
    {
        id:3,
        productName:"Pollo",
        price:750,
        quantly:1,
        img:"/client/media/pollo.png"
    },
    {
        id:4,
        productName:"Mayonesa",
        price:510,
        quantly:1,
        img:"/client/media/mayonesa.png"
    }
]